{% set name = "qetpy" %}
{% set version = "1.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/QETpy-{{ version }}.tar.gz
  sha256: 0f2abbf1d8aa4450cd6fa52ff48e5c69dc2cec33e2a9aaa6de5bbae9090f1c5e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - iminuit >=2.0
    - matplotlib-base
    - numpy
    - python >=3.6
    - scipy
    - sympy
    - astropy
    - pandas
    - packaging

test:
  imports:
    - qetpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/spice-herald/QETpy
  summary: TES Detector Calibration and Analysis Python Tools
  license: GPL-2.0-or-later
  license_file: LICENSE
  description: |
    QETpy (Quasiparticle-trap-assisted Electrothermal-feedback Transition-edge sensors) provides
    a general set of tools for TES-based detector calibration and analysis. It contains submodules
    for noise modeling, IV analysis, complex impedance fitting, nonlinear optimum filter pulse fitting,
    and many other useful detector R&D analysis tools. This package is _NOT_ intended to contain any
    tools specific to a particular analysis. It is also meant to be DAQ independent, meaning it contains
    no IO functionality. It is assumed that the user is able to load their data as NumPy arrays separate
    from QETpy. 

extra:
  recipe-maintainers:
    - slwatkins
